---
# tasks file for nginx
- name: install nginx
  apt:
    pkg: nginx

- name: Copy nginx conf to server
  template: 
    src: default.conf
    dest: /etc/nginx/conf.d

- name: Remove default server directives from nginx conf
  replace:
    path: /etc/nginx/sites-available/default
    regexp: 'default_server'
    replace: ''


- name: Generate certificate keys (Temporary self-signed)
  command: openssl req -new -nodes -x509  -subj '/CN=local/O=MYCOMPANY/C=IR' -days 10 -keyout /etc/ssl/certs/cert.key -out /etc/ssl/certs/cert.crt

- name: Restart nginx
  service:
    name: nginx
    state: restarted



