---
# tasks file for nginx
- name: install nginx
  apt:
    pkg: nginx

- name: Copy nginx conf to server
  template: 
    src: default.conf
    dest: /etc/nginx/conf.d

- name: Edit nginx config file with local variables
  command: "{{ item }}"
  with_items:
    - sed -i "s/USER/{{ usr }}/g" /etc/nginx/conf.d/default.conf
    - sed -i "s/SERVER_NAME/{{ server_name }}/g" /etc/nginx/conf.d/default.conf

- name: Delete default_server directive in nginx conf
  command: sed -i "s/default_server//g" /etc/nginx/sites-available/default

- name: Restart nginx
  service:
    name: nginx
    state: restarted



