---
# tasks file for nginx
- name: install nginx
  apt:
    pkg: nginx

- name: Copy nginx conf to server
  template: 
    src: default.conf
    dest: /etc/nginx/conf.d

- name: Remove default server directives from nginx conf
  replace:
    path: /etc/nginx/sites-available/default
    regexp: 'default_server'
    replace: ''

- name: Restart nginx
  service:
    name: nginx
    state: restarted



