all:
  #vars:
    #ansible_become: yes
    #ansible_become_method: sudo
  children:
    base:
      hosts:
        ApacheSuperSet:
          ansible_host: 192.168.43.235
          ansible_user: "{{ usr }}"
          ansible_ssh_pass: "{{ pass }}"
          ansible_sudo_pass: "{{ pass }}"
          server_name: "192.168.43.235"
