---
# tasks file for ApacheSuperset
- name: Ensure that these software packages are installed
  apt:
    pkg: "{{ packages }}"

- name: Install virtualenv
  pip:
    name: 
      - virtualenv
      - psycopg2

- name: Setup venv with a non-root user
  include: roles/ApacheSuperset/tasks/setup.yml
  become: yes
  become_user: "{{ usr }}"

- name: Copy service file to host
  template:
    src: superset.service
    dest: /home/{{ usr }}

- name: Move service file to systemd dir  
  command: mv superset.service /etc/systemd/system/

- name: Create superset db
  become: yes
  become_method: sudo
  become_user: postgres
  postgresql_db:
    name: superset

- name: Create user with privileges
  become: yes
  become_method: sudo
  become_user: postgres
  postgresql_user:
    db: superset
    name: superset
    password: "{{ dbpass }}" 
    priv: "ALL"
    expires: infinity


- name: Start superset
  service:
    name: superset
    daemon_reload: yes
    state: restarted
