---
- name: Manually create the initial virtualenv
  command: "{{ item }}"
  with_items:
    - python3 -m venv superset

- name: Install dependencies
  pip:
   name:
     - Flask-WTF==0.14.3
     - psycopg2
     - gevent
     - WTForms==2.3.3
     - pyOpenSSL
   virtualenv: /home/{{ usr }}/superset

- name: Install superset into venv
  pip:
    name:
      - apache-superset
    virtualenv: /home/{{ usr }}/superset
    virtualenv_site_packages: yes

- name: Deploy superset config file
  template:
   src: superset_config.py
   dest: ~/superset/lib/python3.8/site-packages/

- name: Copy superset_setup and set permissions
  template:
    src: superset_setup.sh
    dest: ~/
    mode: u+x,g-x,o-x


