---
# handlers file for initdebian
- name: Restart sshd
  service:
    name: sshd
    state: restarted
  when: reboot_required.stat.exists == false

- name: Restart fail2ban
  service:
    name: fail2ban
    state: restarted
  when: reboot_required.stat.exists == false

- name: Restart systemd-resolved
  service:
    name: systemd-resolved
    state: restarted
  when: reboot_required.stat.exists == false